// ============================================================
// Jetdale — Terms of Service
// ============================================================

const sections = [
  {
    title: '1. Acceptance of Terms',
    content: `By accessing or using Jetdale ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, you may not use the Service. These terms apply to all users, including visitors, free tier users, and paid subscribers.`,
  },
  {
    title: '2. Description of Service',
    content: `Jetdale is an AI-powered project planning platform that generates project documentation, architecture recommendations, and development artifacts based on user-provided project descriptions. The Service uses artificial intelligence to analyze project requirements and produce structured deliverables.`,
  },
  {
    title: '3. User Accounts',
    content: `To use Jetdale, you must create an account with accurate and complete information. You are responsible for:

- Maintaining the confidentiality of your account credentials
- All activities that occur under your account
- Notifying us immediately of any unauthorized access
- Ensuring your account information remains current and accurate

We reserve the right to suspend or terminate accounts that violate these terms.`,
  },
  {
    title: '4. Subscriptions & Billing',
    content: `Jetdale offers a free tier and paid Pro subscriptions:

- Free Tier: Limited to 1 project/month, 5 artifacts/project, basic export formats
- Pro Monthly: $49/month, billed monthly, cancel anytime
- Pro Annual: $390/year ($32.50/month), billed annually, cancel anytime

Payments are processed by Stripe (web) or through your app store (iOS/Android). Subscription renewals are automatic. You may cancel at any time, and your access continues through the end of your current billing period. Refunds are not provided for partial billing periods.`,
  },
  {
    title: '5. Intellectual Property',
    content: `Your Content: You retain all rights to the project descriptions, requirements, and other content you provide to Jetdale. You grant us a limited license to process this content solely to provide the Service.

Generated Artifacts: Documents, plans, and other artifacts generated by Jetdale based on your input are owned by you. You may use them for any purpose, including commercial projects.

Our Service: The Jetdale platform, including its design, code, AI models, archetype system, and branding, is owned by Jetdale. You may not copy, modify, or reverse-engineer any part of the Service.`,
  },
  {
    title: '6. AI-Generated Content Disclaimer',
    content: `Jetdale uses AI to generate project documentation and recommendations. You acknowledge that:

- AI-generated content may contain errors, inaccuracies, or omissions
- Generated documents are starting points, not final deliverables
- You are responsible for reviewing and validating all generated content
- Jetdale does not guarantee the accuracy, completeness, or fitness of generated content
- Technical recommendations (stack, architecture, etc.) should be validated by qualified professionals
- Cost and timeline estimates are approximate and may vary significantly`,
  },
  {
    title: '7. Acceptable Use',
    content: `You agree not to use Jetdale to:

- Violate any applicable law or regulation
- Generate content that is illegal, harmful, or infringes on others' rights
- Attempt to access other users' accounts or data
- Reverse-engineer, decompile, or disassemble any part of the Service
- Use automated tools to scrape or extract data from the Service
- Overload or interfere with the Service's infrastructure
- Resell or redistribute the Service without authorization`,
  },
  {
    title: '8. Limitation of Liability',
    content: `To the maximum extent permitted by law, Jetdale and its officers, employees, and affiliates shall not be liable for:

- Any indirect, incidental, special, consequential, or punitive damages
- Any loss of profits, data, or business opportunities
- Any damages arising from reliance on AI-generated content
- Any damages exceeding the amount you paid to Jetdale in the 12 months preceding the claim

The Service is provided "as is" and "as available" without warranties of any kind, either express or implied.`,
  },
  {
    title: '9. Data & Privacy',
    content: `Your use of Jetdale is also governed by our Privacy Policy, which describes how we collect, use, and protect your information. By using the Service, you consent to our data practices as described in the Privacy Policy.`,
  },
  {
    title: '10. Termination',
    content: `Either party may terminate this agreement at any time. You may delete your account through the settings page. We may suspend or terminate your access if you violate these terms. Upon termination:

- Your right to use the Service ceases immediately
- We will retain your data for 30 days, after which it will be permanently deleted
- You may request an export of your data before or during the 30-day period`,
  },
  {
    title: '11. Changes to Terms',
    content: `We may modify these terms at any time. We will notify you of material changes via email or through the Service. Your continued use of Jetdale after changes take effect constitutes acceptance of the updated terms. If you disagree with any changes, you must stop using the Service and delete your account.`,
  },
  {
    title: '12. Governing Law',
    content: `These terms are governed by and construed in accordance with applicable law. Any disputes arising from these terms or your use of the Service shall be resolved through binding arbitration, except where prohibited by law.`,
  },
  {
    title: '13. Contact',
    content: `If you have questions about these Terms of Service, contact us at:

Jetdale
Email: info@donkeyideas.com`,
  },
];

export default function TermsPage() {
  return (
    <article
      style={{
        maxWidth: 760,
        margin: '0 auto',
        padding: '80px 32px 100px',
      }}
    >
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: 12,
          marginBottom: 32,
        }}
      >
        <span style={{ width: 32, height: 1, background: 'var(--accent)', display: 'inline-block' }} />
        <span
          style={{
            fontFamily: "'Space Mono', monospace",
            fontSize: 11,
            textTransform: 'uppercase' as const,
            letterSpacing: '0.15em',
            color: 'var(--accent)',
          }}
        >
          Legal
        </span>
      </div>

      <h1
        style={{
          fontFamily: "'Bricolage Grotesque', -apple-system, sans-serif",
          fontSize: 'clamp(36px, 5vw, 56px)',
          fontWeight: 600,
          letterSpacing: '-0.035em',
          lineHeight: 1.05,
          marginBottom: 16,
        }}
      >
        Terms of Service
      </h1>

      <p
        style={{
          fontFamily: "'Space Mono', monospace",
          fontSize: 11,
          textTransform: 'uppercase' as const,
          letterSpacing: '0.15em',
          color: 'var(--muted)',
          marginBottom: 64,
        }}
      >
        Last updated: May 12, 2026
      </p>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 48 }}>
        {sections.map((section) => (
          <div key={section.title}>
            <h2
              style={{
                fontFamily: "'Bricolage Grotesque', -apple-system, sans-serif",
                fontSize: 24,
                fontWeight: 600,
                letterSpacing: '-0.02em',
                lineHeight: 1.2,
                marginBottom: 16,
              }}
            >
              {section.title}
            </h2>
            <div
              style={{
                fontSize: 15,
                lineHeight: 1.7,
                color: 'var(--muted)',
                whiteSpace: 'pre-line',
              }}
            >
              {section.content}
            </div>
          </div>
        ))}
      </div>
    </article>
  );
}
